apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicasetdemo
  namespace: roboshop
  labels:
    app: replicaset-nginx
    demo: replicatsetdemo
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: Satya
  spec:
    replicas: 2
    selector:
      matchLabels:
       app: replicaset-nginx
       demo: replicatsetdemo
    template:
      metadata:
       namespace: roboshop
       labels: 
        app: replicaset-nginx
        demo: replicatsetdemo
      spec:
        containers:
        - name: nginxreplica
          image: nginx:mainline-alpine3.18-perl 