apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentdemo
  namespace: roadshop
  labels:
   app: deploymentnginx
   demo: deployementnemo
spec:
  replicas: 2
  selector:
    matchLabels:
     app: deploymentnginx
     demo: deployementdemo  
  template:
   metadata:
    labels:
     app: deploymentnginx
     demo: deployementdemo
   spec: 
    containers:
    - name: nginxdpeloyment
      image: nginx
      ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxservice
spec:
  selector:
   app: deploymentnginx
   demo: deployementdemo      
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80