apiVersion: v1
kind: Pod
metadata:
  name: lables-demo
  namespace: roboshop
  lables:
    course: DevOps
    trainer: siva
spec:
  containers:
  - name: lables-test
    image: nginx
    containerports:
    - containerPort: 80