apiVersion: v1
kind: Pod
metadata:
  name: multicontiner-pod
  namespace: roboshop
  labels:
    course: DevOps
    trainer: shivakumar
spec:
  containers:
  - name: nginximage
    image: nginx
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "300"]