apiVersion: v1
kind: Pod
metadata:
  name: env-demo
  namespace: roboshop
  labels:
    course: DevOps
    trainer: shivakumar
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: satya
spec:
  containers:
  - name: nginximage
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: dev
      value: "DEV-SOI"
    - name: 
      value: "SIT-SOI"
  - name: prodnginximage
    image: almalinux:8
    env:
    - name: PODEnv
      value: "POD-SOI"
    command: ["sleep","100"]
