apiVersion: v1
kind: Pod
metadata:
  name: resource-demo
  namespace: roboshop
  labels:
    name: shivakumar
    trainer: DevOps 
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: satya
spec:
  containers:
  - name: resourceimage 
    image: nginx
    ports:
    - containerPort: 80
    resource:
      request:
        CPU: "100m"
        memory: "64Mi"
      limints:
        CPU: "150m"
        memory: "128Mi"
    env:
    - name: DevEnv
      value: "DEV-SOI"
