apiVersion: v1
kind: Pod
metadata:
  name: Podsecret-demo
  namespace: roboshop
  labels:
    course: DevOps
    trainer: shivakumar
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: satya
spec:
  containers:
  - name: nginximage
    image: nginx
    ports:
    - containerPort: 80
  env:
  - name: DevEnv
    value: "DEV-SOI"
  - name: courseconfigMapRef
    valueForm:
     configMapyKeyRef:
      name: devconfigmapRef
      key: trainer
  envFrom:
    configMapRef:
    name: Secret-demo