apiVersion: apps/v1
kind: deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    name: roboshop
    tier: web
  annotations:
    appverion: v1
    jenkinsURL: ""https://github.com/narayanajbs/DevOps_All/blob/main/k8_roboshop/"
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: mongodb
      project: roboshop
      tier: db
  template:
    metadata:
      labels: # these labels are pod labels
        app: mongodb
        project: roboshop
        tier: db
    spec:
      containers:
      - name: mongodb
        image: "/roboshop/mongodb:v1"
        ports:
        - contaierPort: 27017
        imagePullPolicy: Always
---

apiVersion: v1
kind: service
metadata:
  name: mongodbservice
spec:
  type: NodePort
  selector:
   app: mongodb
   project: roboshop
   tier: db
  ports:
  - protocol: TCP
    port: 27017 #service-port
    targetPort: 27017 