apiVersion: v1
kind: Pod
metadata: 
  name: clusterIPdemo
  namesapce: roboshop
  labels:
    app: nginx
    demo: service
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: satya
spec:
  containers:
  - name: clusterIPNginx
    image: nginx
    ports:
    - containerPort: 80
  
---

  apiVersion: v1
  kind: Service
  metadata:
    name: servicenginx
    namesapce: roboshop
  spec:
    selector:
      app: nginx
      demo: service
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80