apiVersion: v1
kind: Pod
metadata:
  name: nodportDemo
  namespace: roboshop
  labels:
    app: nodportNginx
    demo: service
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: satya
spec:
  containers:
  - name: nodeport-demo
    image: nginx
    ports:  
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: NodePort
  selector:
   app: nodportNginx
   demo: service
  ports:
  - protocol: tcp
    port : 80
    targetPort: 80


