apiVersion: v1
kind: Pod
metadata:
  name: loadbalancedemo
  namespace: roboshop
  labels: 
    app: loadbalncernginx
    demo: service
  annotations:
    jenkinsURL: "https://github.com/narayanajbs/DevOps_All/blob/main/k8_resource/02-pods/01-pod.yaml"
    author: satya
spec:
  containers:
  - name: loadbalncernginx
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: devenv
      value: "SOI-Dev"
    - name: envconfig
      valuefrom: 
      - configMapKeyRef:
         name: devconfigmapref
         key: trainer
    envFrom:
    - configMapRef:
       name: devconfigmapref
---
apiVersion: v1
kind: Service
metadata:
  name: serviceloadbalancer
spec:
  type: LoadBalancer
  selector:
   app: loadbalncernginx
   demo: service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80